In [1]:
import cv2
import numpy as np
import math

In [2]:
class Point(object):
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def getX(self):
        return self.x

    def getY(self):
        return self.y


def selectConnects():
    """
    -1,-1:左上
    0,-1:正上
    1,-1:右上
    1,0:右侧
    1,1:右下
    0,1:正下
    -1,1:左下
    -1,0:左测
    """
    return [Point(-1, -1), Point(0, -1), Point(1, -1), Point(1, 0), Point(1, 1),
            Point(0, 1), Point(-1, 1), Point(-1, 0)]  # 八邻域


# 计算像素之间的偏差
def getGrayDiff(img, currentPoint, tmpPoint):
    return abs(int(img[currentPoint.x, currentPoint.y]) - int(img[tmpPoint.x, tmpPoint.y]))

In [3]:
def region_grow(gray_image, seeds, thresh, result):
    # 读取图像的宽高，并建立一个和原图大小相同的seedMark
    height, weight = gray_image.shape
    seedMark = np.zeros(gray_image.shape, dtype=np.uint8)

    # 将定义的种子点放入种子点序列seedList
    seedList = []
    for seed in seeds:
        seedList.append(seed)
    label = 255
    label_count = 0

    # 选择邻域，更改程序默认8邻域
    connects = selectConnects()

    # 逐个点开始生长，生长的结束条件为种子序列为空，即没有生长点
    while len(seedList) > 0:
        # 弹出种子点序列的第一个点作为生长点
        currentPoint = seedList.pop(0)  # 弹出第一个元素
        # 并将生长点对应seedMark点赋值label（1），即为白色
        seedMark[currentPoint.x, currentPoint.y] = label
        label_count += 1

        # 以种子点为中心，八邻域的像素进行比较
        for i in range(len(connects)):
            tmpX = currentPoint.x + connects[i].x
            tmpY = currentPoint.y + connects[i].y
            # 判断是否为图像外的点，若是则跳过。  如果种子点是图像的边界点，邻域点就会落在图像外
            if tmpX < 0 or tmpY < 0 or tmpX >= height or tmpY >= weight:
                continue

            # 判断邻域点和种子点的差值
            grayDiff = getGrayDiff(gray_image, currentPoint, Point(tmpX, tmpY))

            # 如果邻域点和种子点的差值小于阈值并且是没有被分类的点，则认为是和种子点同类，赋值label，
            # 并作为下一个种子点放入seedList
            if grayDiff < thresh and seedMark[tmpX, tmpY] == 0 and result[tmpX, tmpY] == 0:
                seedMark[tmpX, tmpY] = label
                result[tmpX, tmpY] = label
                seedList.append(Point(tmpX, tmpY))
                label_count += 1

    print("label_count: ", label_count)
    return label_count, seedMark, result


In [5]:
image = cv2.imread("test.png", cv2.IMREAD_COLOR)
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

rows, cols = gray_image.shape
result = np.zeros(gray_image.shape)
region_imgs = []
region_dict = {}

for row in range(0, rows, 100):
    for col in range(0, cols, 100):
        if result[row, col] == 255 or gray_image[row, col] < 30:
            continue

        b, g, r = image[row, col]
        color_str = f'b[{b}], g[{g}], r[{r}]'

        seeds = [Point(row, col)]
        label_count, region_img, result = region_grow(gray_image, seeds, 5, result)
        if label_count < 271:
            continue
        region_imgs.append(region_img)

        if region_dict.get(color_str) is None:
            region_dict[color_str] = region_img
        else:
            region_dict[color_str] += region_img

for key in region_dict:
    img_path = "./segment/" + key + ".png"
    filtered_img = region_dict[key]
    # 将 img 生成数组
    # img_a = Image.fromarray(img)

    linesP = cv2.HoughLinesP(filtered_img, 1, np.pi / 180, threshold=5, minLineLength=1, maxLineGap=2)
    print(img_path)

    # 更新 linesP, 如果两点之间距离小于2，则过滤
    new_linesP = []
    for line in linesP:
        x1, y1, x2, y2 = line[0]
        if math.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2) > 2:
            new_linesP.append(line)
    #
    new_linesP = np.array(new_linesP)
    sorted_indices = np.lexsort((new_linesP[:, 0, 1], new_linesP[:, 0, 0]))
    new_linesP = new_linesP[sorted_indices]

    # 遍历
    for line in new_linesP:
        print(line[0])

    cv2.imwrite(img_path, filtered_img)

label_count:  29783
./segment/b[255], g[255], r[255].png
[  0   0  79 150]
[  0   2  79 151]
[  0   4  78 151]
[ 0  8 15  4]
[ 0 10  9  1]
[  0  11  77 151]
[  0  13  73 151]
[  0  14  70 151]
[ 0 16 10  0]
[  0  18  68 151]
[  0  20  67 151]
[  0  22  63 151]
[  0  24  54 151]
[  0  29  36 111]
[  0  32  53 151]
[ 0 37 24 88]
[  0  39  52 151]
[  0  42  50 149]
[  0  43  47 150]
[  0  45  41 137]
[  0  47  40 151]
[  0  50  27 151]
[  0  56  25 151]
[  0  59  24 151]
[  0  63  21 151]
[  0  67  18 151]
[  0  69  14 151]
[  0  78  13 151]
[  0  86  51 151]
[  0  87  11 151]
[  0  92   6 151]
[  0 102   3 135]
[  0 113   4 151]
[  0 115  48 151]
[  0 122  22 151]
[  0 124   0 131]
[  0 132  15 151]
[  0 134   3 151]
[  0 140   0 143]
[  0 144   0 151]
[  1  18  69 151]
[ 1 26 43  1]
[  1  52  15 104]
[  1 136   3 148]
[  1 146   2 151]
[ 2  0 16 26]
[ 2 14 22  0]
[  2 139  14 142]
[ 3  1 22 25]
[  3 114   7 151]
[ 4  0 23 25]
[  4  33  61 151]
[  4  60  37 151]
[  4 119   8 141]
[ 5  0 