In [1]:
import numpy as np

In [2]:
# 从数组构造 ndarray
lines = np.array([[[3281.9, 999.38, 3281.9, 1000.6], [[1226.3, 1294.5, 1225.5, 1291.9]],
                   [[793.2, 1193.1, 793.25, 1200.6]]]])
print(lines)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 3) + inhomogeneous part.

In [43]:
import numpy as np

lines = np.array([[[3281.9, 999.38, 3281.9, 1000.6], [[1226.3, 1294.5, 1225.5, 1291.9]],
                   [[793.2, 1193.1, 793.25, 1200.6]]]])

# sorted_lines = lines[np.lexsort(lines[:, ::-1].T)]
# print(sorted_lines)

# # 提取每个线段的 x1 坐标（第一列）并排序
# sorted_indices = np.argsort(lines[:, :, 0], axis=0)
# 
# # 按照排序后的索引重新排列线段数据
# sorted_lines = lines[sorted_indices]
# 
# # 打印排序后的线段列表
# print(sorted_lines)


# lines = lines[lines[:, 0].argsort()]
# lines = lines[-lines[:, 0].argsort()]


# lines = np.sort(lines, axis=0)
# print(lines)

# data = lines.squeeze(0)
data = lines
idex = np.lexsort([data[:, 2], data[:, 1], data[:, 0]])
sorted_data = data[idex, :]

C:\Users\ping\AppData\Local\Temp\ipykernel_20016\3060192485.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  lines = np.array([[[3281.9, 999.38, 3281.9, 1000.6], [[1226.3, 1294.5, 1225.5, 1291.9]],


In [52]:
data = np.array([[2, 2, 5], [2, 1, 3], [1, 2, 3], [3, 1, 4]])
print(data[:, 2])
idex = np.lexsort([data[:, 2], data[:, 1], data[:, 0]])
# print(idex)
sorted_data = data[idex, :]
sorted_data

[5 3 3 4]


array([[1, 2, 3],
       [2, 1, 3],
       [2, 2, 5],
       [3, 1, 4]])

In [77]:
n1 = np.array([[3281.9, 999.38, 3281.9, 1000.6]])
n2 = np.array([[1226.3, 1294.5, 1225.5, 1291.9]])
n3 = np.array([[793.2, 1193.1, 793.25, 1200.6]])
lines = np.array([n1, n2, n3])
print(lines)

data = lines.squeeze()

# print(data[:, 2])
index = np.lexsort([data[:, 2], data[:, 1], data[:, 0]])
print(index)
sorted_data = data[idex, :]
print(sorted_data)

[[[3281.9   999.38 3281.9  1000.6 ]]

 [[1226.3  1294.5  1225.5  1291.9 ]]

 [[ 793.2  1193.1   793.25 1200.6 ]]]
[2 1 0]
[[ 793.2  1193.1   793.25 1200.6 ]
 [1226.3  1294.5  1225.5  1291.9 ]
 [3281.9   999.38 3281.9  1000.6 ]]
